export const SITE = {
  name: "SOLVEEK",
  legalName: "Solveek Digital Solutions",
  tagline: "Build. Connect. Grow.",
  category: "Digital Growth Partner",
  description:
    "Solveek is a digital growth partner. We help businesses get found, connect with customers, and grow.",
  url: "https://www.solveek.com",
  ogImage: "/og.png",
  email: "hello@solveek.com",
  salesEmail: "sales@solveek.com",
  supportEmail: "support@solveek.com",
  phone: "+233 24 637 0261",
  emergencyPhone: "+233 24 637 0261",
  social: {
    linkedin: "https://linkedin.com/company/solveek",
    facebook: "https://facebook.com/solveek",
    instagram: "https://instagram.com/solveek",
  },
} as const;

/** Local brand / project assets. Extra keys kept for legacy pages still in the tree. */
export const IMAGES = {
  process: "/images/process-tech-bg.jpg",
  heroNetwork: "/images/hero-network.png",
  ecosystemHeader: "/images/ecosystem-header.png",
  ecosystemTeam: "/images/ecosystem-team.jpg",
  workHeader: "/images/work-header.png",
  aboutHeader: "/images/about-header.png",
  contactHeader: "/images/contact-header.png",
  chiliHaus: "/images/project-chili-haus-home.jpg",
  dziFoods: "/images/project-dzi-foods-home.jpg",
  luxuryStrand: "/images/project-luxury-strand-home.jpg",
  booksandyou: "/images/project-booksandyou-home.jpg",
  northline: "/images/project-northline-commerce.png",
  atelier: "/images/project-atelier-social.png",
  lumen: "/images/project-lumen-branding.png",
  hero: "/images/process-tech-bg.jpg",
  team: "/images/process-tech-bg.jpg",
  teamAlt: "/images/process-tech-bg.jpg",
  office: "/images/process-tech-bg.jpg",
  design: "/images/process-tech-bg.jpg",
  code: "/images/process-tech-bg.jpg",
  ecommerce: "/images/project-northline-commerce.png",
  social: "/images/project-atelier-social.png",
  saas: "/images/process-tech-bg.jpg",
  meeting: "/images/process-tech-bg.jpg",
  product: "/images/process-tech-bg.jpg",
  analytics: "/images/process-tech-bg.jpg",
  portrait: "/images/process-tech-bg.jpg",
  portraitAlt: "/images/process-tech-bg.jpg",
  portraitSoft: "/images/process-tech-bg.jpg",
} as const;
